version: "3.7"

services:

  #PHP Service
  project-blogging-php:
    build:
      context: docker/php-fpm
      args:
        user: nico
        uid: 1000
    container_name: project-blogging-php
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/conf/php/php.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - project-blogging-network

  #Nginx Service
  project-blogging-nginx:
    image: nginx:alpine
    container_name: project-blogging-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www/public
      - ./var/log:/var/log/nginx
      - ./docker/conf/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - project-blogging-network


  #MySQL Service
  project-blogging-mysql:
    image: mysql:5.7.22
    container_name: project-blogging-mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=write_model_blogging_core
      - MYSQL_USER=user
      - MYSQL_PASSWORD=User!!Pass
    volumes:
      - blogging:/var/lib/mysql/
      - ./docker/conf/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - project-blogging-network


  #ElasticSearch Service
  project-blogging-elasticsearch:
    image: elasticsearch:7.6.2
    container_name: project-blogging-elasticsearch
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
    networks:
      - project-blogging-network


#Volumes
volumes:
  blogging:
    driver: local


#Docker Networks
networks:
  project-blogging-network:
    driver: bridge

